### ISSUE TITLE
Object reference not set to an instance of an object Exception

### ISSUE THREAD

**Issue by terzano** [GlobalPhone/GlobalPhone#22]
Hi, I am getting an object reference exception using the static method Parse. 
I set the DbPath to the json file (I had no trouble generating it successfully with the DbGen tool. 
Any help is greatly appreciated. 
```
"message": "Object reference not set to an instance of an object.", 
"stackTrace": "     at GlobalPhone.Territory.Possible(String str)
   at GlobalPhone.Territory.ParseNationalString(String str)
   at GlobalPhone.Parsing.Parse(String str, String territoryName)
   at GlobalPhone.Context.Parse(String str, String territoryName)
   at GlobalPhone.GlobalPhone.Parse(String number, String territoryName)
```

**Comment by wallymathieu** [comment]
I've added a branch where we can see the regression : https://github.com/GlobalPhone/GlobalPhone/tree/null_reference_exception

**Comment by wallymathieu** [comment]
The issue looks like it's due to change of xml format in [libphonenumber](https://github.com/googlei18n/libphonenumber). 

A quick-fix is to either download an old version of the xml and generate a new db from that or use something else. It looks like there is a stable c# port [libphonenumber-csharp](https://github.com/twcclegg/libphonenumber-csharp) that could be used? It looks like @twcclegg puts a lot of effort into it. However, I've not tried out.

**Comment by terzano** [comment]
Thank you for the suggestion. The port works quite well.

**Comment by wallymathieu** [comment]
Another alternative is to provide extension methods et.c. in order to give a nicer c# API for libphonenumber, see https://github.com/twcclegg/libphonenumber-csharp/issues/57#issuecomment-370910150
